### ISSUE TITLE
`currentScope[attribs[PROP]].push is not a function` error when using `parse` even when wrapped in a try/catch

### ISSUE THREAD

**Issue by lancesnider** [indix/web-auto-extractor#29]
When I try to parse this page (https://www.discountnaturalhealth.com/bilberry-eye-support-advanced-30-tablets-blackmores/), I get the following error: 

```
contentScript.bundle.js:190 TypeError: currentScope[attribs[PROP]].push is not a function
    at Object.onopentag (contentScript.bundle.js:146442:37)
    at Parser.onopentagend (contentScript.bundle.js:48652:23)
    at Tokenizer._stateBeforeAttributeName (contentScript.bundle.js:49170:19)
    at Tokenizer._parse (contentScript.bundle.js:49664:18)
    at Tokenizer.write (contentScript.bundle.js:49639:10)
    at Tokenizer.end (contentScript.bundle.js:49817:21)
    at Parser.end (contentScript.bundle.js:48833:21)
    at exports.default (contentScript.bundle.js:146528:44)
    at Object.parse (contentScript.bundle.js:146253:48)
    at isCategoryPage (contentScript.bundle.js:143319:87)
```

You can see in the W3C validator that this page has some errors, including a stray `</i>` tag: https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.discountnaturalhealth.com%2Fbilberry-eye-support-advanced-30-tablets-blackmores%2F

Here's the code you can use to reproduce the issue: 

```
try {
  const parsed = WAE().parse(document?.body?.innerHTML);
} catch {
}
```

I would expect the `parse` to fail due to bad html, but I would have expected it to `catch`, rather than causing an error.

**Comment by lancesnider** [comment]
I'm being crazy. Please ignore me. :) 

Turns out I had 2 places where I used `parse` and one of them wasn't wrapped in a `try/catch`.
